import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';

const helvetic = localFont({
  src: './assets/font/HelveticaNeueRoman.otf'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={helvetic.className}>{children}</body>
    </html>
  );
}
